name: kalam_news_publication
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  responsive_sizer: ^3.3.1
  device_preview: ^1.1.0
  pin_code_fields: ^8.0.1
  timer_count_down: ^2.2.2
  fluttertoast: ^8.2.4
  http: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.0
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  image_picker: ^1.0.8
  image_cropper: ^5.0.0
  image: ^4.1.7
  flutter_graph_view: ^1.0.4
  lottie: ^3.1.0
  flutter_dash: ^1.0.0
  razorpay_flutter: ^1.3.6
  share_plus: ^7.2.2
  url_launcher: ^6.1.9


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/fonts/
    - assets/bottom_bar_icon/
    - assets/animations/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueMedium.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeueBlack.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeueHeavy.otf
          weight: 600
        - asset: assets/fonts/HelveticaNeueBold.otf
          weight: 700